name: serene_track
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  tab_container: ^3.5.3
  riverpod_annotation: ^2.3.5
  flutter_gen_runner: ^5.5.0+1
  freezed_annotation: ^2.4.2
  dio: ^5.5.0
  flutter_launcher_icons: ^0.13.1
  intl: any
  shared_preferences: ^2.2.3
  audioplayers: ^6.0.0
  flutter_native_splash: ^2.4.0
  health: ^11.1.0
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  flutter_datetime_picker_plus: ^2.2.0
  line_icons: ^2.0.3
  enum_to_string: ^2.0.1
  flutter_vibrate: ^1.3.0
  confetti: ^0.6.0-nullsafetys
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/sounds/timeup.mp3
    
    # 環境変数
    - .env.development
    - .env.production

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/serene_track_icon.png"

flutter_native_splash:
  image: "assets/images/icons/serene_track_icon.png"
  color: "FFFFFF"
